version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: levy-calibration-api:latest
    container_name: levy-api
    ports:
      - "8000:8000"
    environment:
      # Application settings
      - LOG_LEVEL=info
      - API_VERSION=1.0.0

      # Model settings
      - DEFAULT_MODEL=VarianceGamma
      - WARMUP_ON_STARTUP=false

      # Performance settings
      - TF_CPP_MIN_LOG_LEVEL=2  # Suppress TensorFlow warnings
      - OMP_NUM_THREADS=4       # OpenMP threads for CPU inference

    volumes:
      # Mount models as read-only for security
      - ./models/calibration_net:/app/models/calibration_net:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    restart: unless-stopped

    # Resource limits (adjust based on your infrastructure)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

    networks:
      - levy-network

networks:
  levy-network:
    driver: bridge
